server {
    listen 80;
    server_name careeros.local;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name careeros.local;

    ssl_certificate /Users/greg/Code/Local/careeros/nginx/careeros.local.pem;
    ssl_certificate_key /Users/greg/Code/Local/careeros/nginx/careeros.local-key.pem;

    location / {
        root /Users/greg/Code/Local/careeros/frontend/dist;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://127.0.0.1:3005;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
